import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import axios from "axios";
import { useState } from "react";
import Weather from "../../components/Weather";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=328a999c9199584ca8a1c676b673b9f3
  `;
  console.log(city);

  const fetchWeather = async (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((rensponse) => {
      setWeather(rensponse.data);
      console.log(rensponse.data);
    });
  };

  return (
    <>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="weather">Weather App</h1>
      <form onSubmit={fetchWeather}>
        <input
          type="text"
          placeholder="Search"
          onChange={(e) => setCity(e.target.value)}
        />
        <button>Search</button>
      </form>
      {weather.main && <Weather data={weather} />}
    </>
  );
}
